export const UP = 'UP'
export const DOWN = 'DOWN'

export const TOP = 'TOP'
export const BOTTOM = 'BOTTOM'
export const RIGHT = 'RIGHT'
export const LEFT = 'LEFT'

export const TOPIC = 'TOPIC'
export const BRANCH = 'BRANCH'
export const GROUP = 'GROUP'
export const CONN = 'CONN'

export const MAP = 'MAP'
export const ORG_U = 'ORG_U'
export const ORG_D = 'ORG_D'
export const LOGIC_R = 'LOGIC_R'
export const LOGIC_L = 'LOGIC_L'
export const TREE_L = 'TREE_L'
export const TREE_R = 'TREE_R'